# Generated by Django 4.0.2 on 2022-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_alter_apptemp_gid_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
