# Generated by Django 4.0.2 on 2022-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_alter_apptemp_gid_alter_car_condicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condicao',
            field=models.CharField(max_length=255),
        ),
    ]
